"""Type stubs for affine 2.4.0, which ships no annotations.

``Affine`` subclasses a dynamically created ``namedtuple``, so pyright infers
every coefficient (``.a``, ``.e``, ...) as ``Unknown``. That leaks into every
transform calculation in rastera. Only the surface rastera uses is stubbed.
"""

from typing import NamedTuple, overload

__all__ = ["Affine"]

EPSILON: float

class AffineError(Exception): ...
class TransformNotInvertibleError(AffineError): ...
class UndefinedRotationError(AffineError): ...

def cos_sin_deg(deg: float) -> tuple[float, float]: ...

class Affine(NamedTuple):
    a: float
    b: float
    c: float
    d: float
    e: float
    f: float
    g: float = 0.0
    h: float = 0.0
    i: float = 1.0

    @classmethod
    def from_gdal(
        cls, c: float, a: float, b: float, f: float, d: float, e: float
    ) -> Affine: ...
    @classmethod
    def identity(cls) -> Affine: ...
    @classmethod
    def translation(cls, xoff: float, yoff: float) -> Affine: ...
    @classmethod
    def scale(cls, *scaling: float) -> Affine: ...
    @classmethod
    def shear(cls, x_angle: float = 0, y_angle: float = 0) -> Affine: ...
    @classmethod
    def rotation(
        cls, angle: float, pivot: tuple[float, float] | Affine | None = None
    ) -> Affine: ...
    @classmethod
    def permutation(cls, *scaling: float) -> Affine: ...
    def to_gdal(self) -> tuple[float, float, float, float, float, float]: ...
    def to_shapely(self) -> tuple[float, float, float, float, float, float]: ...
    @property
    def xoff(self) -> float: ...
    @property
    def yoff(self) -> float: ...
    @property
    def determinant(self) -> float: ...
    @property
    def eccentricity(self) -> float: ...
    @property
    def rotation_angle(self) -> float: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def is_rectilinear(self) -> bool: ...
    @property
    def is_conformal(self) -> bool: ...
    @property
    def is_orthonormal(self) -> bool: ...
    @property
    def is_degenerate(self) -> bool: ...
    @property
    def is_proper(self) -> bool: ...
    @property
    def column_vectors(
        self,
    ) -> tuple[tuple[float, float], tuple[float, float], tuple[float, float]]: ...
    def almost_equals(self, other: Affine, precision: float = ...) -> bool: ...
    def itransform(self, seq: list[tuple[float, float]]) -> None: ...
    @overload
    def __mul__(self, other: Affine) -> Affine: ...
    @overload
    def __mul__(self, other: tuple[float, float]) -> tuple[float, float]: ...
    # Deprecated upstream, and asserts other is not an Affine.
    def __rmul__(self, other: tuple[float, float]) -> tuple[float, float]: ...
    def __invert__(self) -> Affine: ...
    def __gt__(self, other: object) -> bool: ...
    def __getnewargs__(
        self,
    ) -> tuple[float, float, float, float, float, float, float, float, float]: ...

identity: Affine

def loadsw(s: str) -> Affine: ...
def dumpsw(obj: Affine) -> str: ...
